### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by txtincorporated** [txtincorporated/rest-api-with-user-auth#4]
TODO:
- [x] get user mgt./auth working properly on all routes
- [x] separate test db from dev db
- [x] add user mgt./auth e2e
- [ ] update pre-existing tests to work with user resource, authentication and validation routes

**Comment by txtincorporated** [comment]
Something hinky about that last auth test.  It should be failing but says it has passed.
